/* add at least 3 records into each table */
insert into Products (ID, Name, Price) values (1, 'Bag', 50);
insert into Products (ID, Name, Price) values (2, 'Water', 2);
insert into Products (ID, Name, Price) values (3, 'Pencil', 3);

insert into Orders (ID, ProductID, CustomerID) values (1, 1, 1);
insert into Orders (ID, ProductID, CustomerID) values (2, 1, 2);
insert into Orders (ID, ProductID, CustomerID) values (3, 2, 3);

insert into Customers (ID, Firstname, Lastname, CardNumber) values (1, 'Bob', 'Bobby', 100);
insert into Customers (ID, Firstname, Lastname, CardNumber) values (2, 'Bill', 'Heily', 200);
insert into Customers (ID, Firstname, Lastname, CardNumber) values (3, 'Jim', 'Jones', 300);

/* add product iPhone priced at $200 */
insert into Products (ID, Name, Price) values (4, 'iPhone', 200);

/* add customer Tina Smith */
insert into Customers (ID, Firstname, Lastname, CardNumber) values (4, 'Tina', 'Smith', 400);

/* create order for Tina Smith bought an iPhone */
insert into Orders (ID, ProductID, CustomerID) values (4, 4, 4);

/* report all orders by Tina Smith */
select * from Orders where CustomerID = 4;

/* report all revenue generated by sales of iPhone  -- subquery*/
select sum(a.price)
from Products as a
	join Orders as b on b.ProductID = a.ProductID
where a.Name = 'iPhone';

/* increase the price of iPhone to $250 -- update table */
update Products
set Price = 250
where ID = 4;